language: php 
php:
        7.4.7
script:
        echo "test"
services:
  - docker
before_install:
        - docker build -t ubnt docker/task/zabbix
deploy:
  provider: script
  script: bash image_push docker/task/zabbix
  on:
    branch: master
