language: php 
php:
        7.4.7
script:
        echo "test"
services:
  - docker
before_install:
        - docker build -t bshavlo/zbx-psql-ngx docker/task/zabbix
deploy:
  provider: script
  script: bash docker/task/zabbix/image_push
  on:
    branch: master
